version: "3.8"

services:
    sails-mongo:
        build: ./data
        container_name: sails-mongo
        ports:
            - "27020:27017"
    sails-app:
        build: .
        container_name: sails-app
        ports:
            - "5000:1337"
        depends_on: 
            - sails-mongo
        environment:
            - NODE_ENV=PROD
        restart: "always"